apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: { { .Values.paths.client } }
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{.Values.ports.client}}
          - path: {{ .Values.paths.api}}
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: {{.Values.ports.server}}
